{
  config,
  lib,
  pkgs,
  ...
}:
let
  # Tests replace only this exact digest reference, leaving the Compose topology
  # identical to production while avoiding a registry dependency in VM tests.
  productionImage = "docker.io/library/nginx@sha256:30f1c0d78e0ad60901648be663a710bdadf19e4c10ac6782c235200619158284";
  composeFile = pkgs.writeText "mini-pc-compose.yaml" (
    builtins.replaceStrings [ productionImage ] [ config.my.application.image ] (
      builtins.readFile ../application/compose.yaml
    )
  );
in
{
  options.my.application.image = lib.mkOption {
    type = lib.types.str;
    default = productionImage;
    description = "Immutable application image; tests may override with a local preloaded image";
  };

  config = {
    environment.systemPackages = [ pkgs.docker-compose ];
    systemd.tmpfiles.rules = [
      "d /var/lib/mini-pc/nginx 0750 root root -"
      # Secret values are installed at runtime, never generated by Nix.
      "d /var/lib/mini-pc/secrets 0700 root root -"
    ];
    systemd.services.mini-pc-application = {
      description = "Mini-PC Docker Compose application";
      wantedBy = [ "multi-user.target" ];
      after = [
        "docker.service"
        "network-online.target"
      ];
      wants = [ "network-online.target" ];
      requires = [ "docker.service" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        WorkingDirectory = "/var/lib/mini-pc";
        ExecStart = "${pkgs.docker-compose}/bin/docker-compose -f ${composeFile} up -d --remove-orphans --wait";
        ExecStop = "${pkgs.docker-compose}/bin/docker-compose -f ${composeFile} down";
        TimeoutStartSec = 300;
        TimeoutStopSec = 120;
      };
    };
  };
}
